version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Workflow files stored in the default location of `.github/workflows`
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
